all: 1a_bin 1b_bin 1c_bin 2a_bin 3a_bin 3a_bin 3b_bin 3c_bin

1a_bin:1a.c
	gcc 1a.c -o 1a_bin -l bcm2835
1b_bin:1b.c
	gcc 1b.c -o 1b_bin -l bcm2835
1c_bin:1c.c
	gcc 1c.c -o 1c_bin -l bcm2835
2a_bin:2a.c
	gcc 2a.c -o 2a_bin -l bcm2835
2b_bin:2b.c
	gcc 2b.c -o 2b_bin -l bcm2835
3a_bin:3a.c
	gcc 3a.c -o 3a_bin -l bcm2835
3b_bin:3b.c
	gcc 3b.c -o 3b_bin -l bcm2835
3c_bin:3c.c
	gcc 3c.c -o 3c_bin -l bcm2835